name: bucket_game_flutter
description: A simple game.
version: 1.0.0

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ball.png
    - assets/bucket.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
